#!/bin/bash
# update yum just in case
yum update -y
# get node into yum
curl --silent --location https://deb.nodesource.com/setup_16.x | bash -
# install node and npm in one line
yum install -y nodejs
# install pm2 to restart node app
npm i -g pm2@2.4.3
